
ALTER TABLE usuarios
ALTER COLUMN role TYPE VARCHAR(30);

ALTER TABLE usuarios
    ALTER COLUMN role SET DEFAULT 'ROLE_ALUNO';

ALTER TABLE usuarios
    ALTER COLUMN role SET NOT NULL;

DROP TYPE IF EXISTS user_role;
